//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Ugly.Data.Mapping
{
    public partial class Duplicate1Map
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Ugly.Data.Entities.Duplicate1>
    {
        public Duplicate1Map()
        {
            // table
            ToTable("Duplicate", "Ugly");

            // keys
            HasKey(t => t.DuplicateID);

            // Properties
            Property(t => t.DuplicateID)
                .HasColumnName("DuplicateID")
                .IsRequired();
            Property(t => t.Name)
                .HasColumnName("Name")
                .HasMaxLength(50)
                .IsRequired();

            // Relationships

            InitializeMapping();
        }
    }
}

