<?xml version="1.0" encoding="utf-8"?>
<Database Name="Sample" Class="SampleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=zeus;Initial Catalog=Sample;Integrated Security=True" SettingsObjectName="LinqToSqlShared.DbmlObjectModel.Tests.Properties.Settings" SettingsPropertyName="SampleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Priority" Member="Priorities">
    <Type Name="Priority">
      <Column Name="PriorityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PriorityName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Priority_Task" Member="Tasks" OtherKey="PriorityID" Type="Task" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="Role" ThisKey="RoleID" Type="Role" IsForeignKey="true" />
      <Association Name="User_UserRole" Member="User" ThisKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="UserRoles" OtherKey="RoleID" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="Status">
    <Type Name="Status">
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StatusName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Status_Task" Member="Tasks" OtherKey="StatusID" Type="Task" />
    </Type>
  </Table>
  <Table Name="dbo.Task" Member="Tasks">
    <Type Name="Task">
      <Column Name="TaskID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PriorityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CompleteDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AssignedID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Task_TaskExtended" Member="TaskExtended" OtherKey="TaskID" Type="TaskExtended" Cardinality="One" />
      <Association Name="Priority_Task" Member="Priority" ThisKey="PriorityID" Type="Priority" IsForeignKey="true" />
      <Association Name="Status_Task" Member="Status" ThisKey="StatusID" Type="Status" IsForeignKey="true" />
      <Association Name="User_Task" Member="User" ThisKey="CreatedID" Type="User" IsForeignKey="true" />
      <Association Name="User_Task1" Member="User1" ThisKey="AssignedID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaskExtended" Member="TaskExtendeds">
    <Type Name="TaskExtended">
      <Column Name="TaskID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Browser" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="OS" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="Task_TaskExtended" Member="Task" ThisKey="TaskID" Type="Task" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_UserRole" Member="UserRoles" OtherKey="UserID" Type="UserRole" />
      <Association Name="User_Task" Member="Tasks" OtherKey="CreatedID" Type="Task" />
      <Association Name="User_Task1" Member="Tasks1" OtherKey="AssignedID" Type="Task" />
    </Type>
  </Table>
  <Table Name="dbo.ActiveUser" Member="ActiveUsers">
    <Type Name="ActiveUser">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetEmail" Method="GetEmail">
    <Parameter Name="userName" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(150)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.MarkTaskComplete" Method="MarkTaskComplete">
    <Parameter Name="taskId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetMyTasks" Method="GetMyTasks">
    <Parameter Name="userID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetMyTasksResult">
      <Column Name="TaskID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PriorityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CompleteDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AssignedID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>