//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated using CSLA 3.7.X CodeSmith Templates.
//	   Changes to this template will not be lost.
//
//     Template: Criteria.cst
//     Template website: http://code.google.com/p/codesmith/
// </autogenerated>
//------------------------------------------------------------------------------
#region using declarations

using System;

#endregion

namespace PetShop.Business
{
	public partial class OrderCriteria
    {
        #region Custom Critiera

        public string UserId
        {
            get { return GetValue<string>("UserId"); }
            set { _bag["UserId"] = value; }
        }

        #endregion
    }
}