//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated using CodeSmith: v5.2.2, CSLA Templates: v3.0.0.1817, CSLA Framework: v3.8.4.
//       Changes to this template will not be lost.
//
//     Template: SwitchableObject.cst
//     Template website: http://code.google.com/p/codesmith/
// </autogenerated>
//------------------------------------------------------------------------------
#region Using declarations

using System;
using Csla;

#endregion

namespace PetShop.Business
{
    public partial class Profile
    {
        #region Business Rules

        /// <summary>
        /// All custom rules need to be placed in this method.
        /// </summary>
        /// <returns>Return true to override the generated rules; If false generated rules will be run.</returns>
        protected bool AddBusinessValidationRules()
        {
            // TODO: add validation rules
            //ValidationRules.AddRule(RuleMethod, "");

            return false;
        }

        #endregion

        #region Authorization Rules

        /// <summary>
        /// Allows the specification of CSLA based authorization rules.  Specifies what roles can 
        /// perform which operations for a given business object
        /// </summary>
        protected static void AddObjectAuthorizationRules()
        {
            //// More information on these rules can be found here (http://www.devx.com/codemag/Article/40663/1763/page/2).

            //string[] canWrite = { "AdminUser", "RegularUser" };
            //string[] canRead = { "AdminUser", "RegularUser", "ReadOnlyUser" };
            //string[] admin = { "AdminUser" };

            // AuthorizationRules.AllowCreate(typeof(Profile), admin);
            // AuthorizationRules.AllowDelete(typeof(Profile), admin);
            // AuthorizationRules.AllowEdit(typeof(Profile), canWrite);
            // AuthorizationRules.AllowGet(typeof(Profile), canRead);

            //// UniqueID
            // AuthorizationRules.AllowWrite(_uniqueIDProperty, canWrite);
            // AuthorizationRules.AllowRead(_uniqueIDProperty, canRead);

            //// Username
            // AuthorizationRules.AllowRead(_usernameProperty, canRead);

            //// ApplicationName
            // AuthorizationRules.AllowRead(_applicationNameProperty, canRead);

            //// IsAnonymous
            // AuthorizationRules.AllowRead(_isAnonymousProperty, canRead);

            //// LastActivityDate
            // AuthorizationRules.AllowRead(_lastActivityDateProperty, canRead);

            //// LastUpdatedDate
            // AuthorizationRules.AllowRead(_lastUpdatedDateProperty, canRead);

// NOTE: Many-To-Many support coming soon.
            //// Accounts
            // AuthorizationRules.AllowRead(_accountsProperty, canRead);

            //// Carts
            // AuthorizationRules.AllowRead(_cartsProperty, canRead);

        }
        #endregion

        #region Custom Factory Methods

#if !SILVERLIGHT
        public static Profile GetByUsername(System.String username)
        {
            var criteria = new ProfileCriteria { Username = username };

            return DataPortal.Fetch<Profile>(criteria);
        }
#else
        public static void GetByUsername(System.String username, EventHandler<DataPortalResult<Profile>> handler)
        {
            var criteria = new ProfileCriteria{Username = username};
        
            var dp = new DataPortal< Profile >();
            dp.FetchCompleted += handler;
            dp.BeginFetch(criteria);
        }
#endif

        #endregion

        #region Custom Business Methods

        private static readonly PropertyInfo<CartList> _shoppingCart = RegisterProperty<CartList>(p => p.ShoppingCart, Csla.RelationshipTypes.LazyLoad);
        public CartList ShoppingCart
        {
            get
            {
                if (!FieldManager.FieldExists(_shoppingCart))
                {
#if SILVERLIGHT || NETFX_CORE
                    MarkBusy();
                    
                    if(IsNew)
                        CartList.NewListAsync().ContinueWith(c =>
                        {
                            LoadProperty(_shoppingCart, c.Result);

                            MarkIdle();
                            OnPropertyChanged(_shoppingCart);
                        });
                    else
                        CartList.GetCartAsync(UniqueID, false).ContinueWith(c =>
                        {
                            LoadProperty(_shoppingCart, c.Result);

                            MarkIdle();
                            OnPropertyChanged(_shoppingCart);
                        });
#else
                    if (IsNew)
                        LoadProperty(_shoppingCart, CartList.NewList());
                    else

                        LoadProperty(_shoppingCart, CartList.GetCart(UniqueID, true));
#endif
                }

                return GetProperty(_shoppingCart);
            }
        }

        private static readonly PropertyInfo<CartList> _wishList = RegisterProperty<CartList>(p => p.WishList, Csla.RelationshipTypes.LazyLoad);
        public CartList WishList
        {
            get
            {
                if (!FieldManager.FieldExists(_wishList))
                {
#if SILVERLIGHT || NETFX_CORE
                    MarkBusy();
                    
                    if(IsNew)
                        CartList.NewListAsync().ContinueWith(c =>
                        {
                            LoadProperty(_wishList, c.Result);

                            MarkIdle();
                            OnPropertyChanged(_wishList);
                        });
                    else
                        CartList.GetCartAsync(UniqueID, false).ContinueWith(c =>
                        {
                            LoadProperty(_wishList, c.Result);

                            MarkIdle();
                            OnPropertyChanged(_wishList);
                        });
#else
                    if (IsNew)
                        LoadProperty(_wishList, CartList.NewList());
                    else

                        LoadProperty(_wishList, CartList.GetCart(UniqueID, false));
#endif
                }

                return GetProperty(_wishList);
            }
        }

        #endregion
    }
}