//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Petshop.Data.Mapping
{
    public partial class ItemMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Petshop.Data.Entities.Item>
    {
        public ItemMap()
        {
            // table
            ToTable("Item", "dbo");

            // keys
            HasKey(t => t.ItemId);

            // Properties
            Property(t => t.ItemId)
                .HasColumnName("ItemId")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.None)
                .HasMaxLength(10)
                .IsRequired();
            Property(t => t.ProductId)
                .HasColumnName("ProductId")
                .HasMaxLength(10)
                .IsRequired();
            Property(t => t.ListPrice)
                .HasColumnName("ListPrice")
                .HasPrecision(10, 2)
                .IsOptional();
            Property(t => t.UnitCost)
                .HasColumnName("UnitCost")
                .HasPrecision(10, 2)
                .IsOptional();
            Property(t => t.Supplier)
                .HasColumnName("Supplier")
                .IsOptional();
            Property(t => t.Status)
                .HasColumnName("Status")
                .HasMaxLength(2)
                .IsOptional();
            Property(t => t.Attr1)
                .HasColumnName("Attr1")
                .HasMaxLength(80)
                .IsOptional();
            Property(t => t.Attr2)
                .HasColumnName("Attr2")
                .HasMaxLength(80)
                .IsOptional();
            Property(t => t.Attr3)
                .HasColumnName("Attr3")
                .HasMaxLength(80)
                .IsOptional();
            Property(t => t.Attr4)
                .HasColumnName("Attr4")
                .HasMaxLength(80)
                .IsOptional();
            Property(t => t.Attr5)
                .HasColumnName("Attr5")
                .HasMaxLength(80)
                .IsOptional();
            Property(t => t.Image)
                .HasColumnName("Image")
                .IsOptional();
            Property(t => t.Image50)
                .HasColumnName("Image50")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.ImageMax)
                .HasColumnName("ImageMax")
                .IsOptional();

            // Relationships
            HasRequired(t => t.Product)
                .WithMany(t => t.Items)
                .HasForeignKey(d => d.ProductId)
                .WillCascadeOnDelete(false);
            HasOptional(t => t.Supplier1)
                .WithMany(t => t.Items)
                .HasForeignKey(d => d.Supplier)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}
