//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Ugly.Data.Entities
{
    public partial class Department
    {
        public Department()
        {
            EmployeeDepartmentList = new List<EmployeeDepartment>();
        }

        public int DepartmentId { get; set; }
        public System.Byte[] Name { get; set; }
        public System.Byte[] Description { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }

        public virtual Employee CreatedByEmployee { get; set; }
        public virtual Employee UpdatedByEmployee { get; set; }
        public virtual ICollection<EmployeeDepartment> EmployeeDepartmentList { get; set; }
    }
}