
'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a CodeSmith Template.
'
'     DO NOT MODIFY contents of this file. Changes to this
'     file will be lost if the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Linq
Imports System.Linq
Imports System.Runtime.CompilerServices
Imports CodeSmith.Data.Linq
Imports CodeSmith.Data.Linq.Dynamic

Namespace PetShop.Core.Data
    ''' <summary>
    ''' The query extension class for Inventory.
    ''' </summary>
    Public Module InventoryExtensions
        ''' <summary>
        ''' Gets an instance by the primary key.
        ''' </summary>
        <System.Runtime.CompilerServices.Extension()> _
        Public Function GetByKey(ByVal queryable As IQueryable(Of PetShop.Core.Data.Inventory), ByVal itemId As String) As PetShop.Core.Data.Inventory

            Dim entity As System.Data.Linq.Table(Of PetShop.Core.Data.Inventory) = CType(queryable, Table(Of PetShop.Core.Data.Inventory))
            If (entity IsNot Nothing AndAlso entity.Context.LoadOptions Is Nothing) Then
                Return Query.GetByKey.Invoke(DirectCast(entity.Context, PetShop.Core.Data.PetshopDataContext), itemId)
            End If

            Return queryable.FirstOrDefault(Function(i)i.ItemId = itemId)
        End Function
        
        ''' <summary>
        ''' Immediately deletes the entity by the primary key from the underlying data source with a single delete command.
        ''' </summary>
        ''' <param name="table">Represents a table for a particular type in the underlying database containing rows are to be deleted.</param>
        ''' <returns>The number of rows deleted from the database.</returns>
        <System.Runtime.CompilerServices.Extension()> _
        Public Function Delete(ByVal table As System.Data.Linq.Table(Of PetShop.Core.Data.Inventory), ByVal itemId As String) As Integer
            Return table.Delete(Function(i)i.ItemId = itemId)
        End Function

        ''' <summary>
        ''' Gets a query for <see cref="PetShop.Core.Data.Inventory"/>.
        ''' </summary>
        ''' <param name="queryable">Query to append where clause.</param>
        ''' <param name="itemId">ItemId to search for.</param>
        ''' <returns>IQueryable with additional where clause.</returns>
        <System.Runtime.CompilerServices.Extension()> _
        Public Function ByItemId(ByVal queryable As IQueryable(Of PetShop.Core.Data.Inventory), ByVal itemId As String) As IQueryable(Of PetShop.Core.Data.Inventory)
            Return queryable.Where(Function(i)i.ItemId = itemId)
        End Function
        
        ''' <summary>
        ''' Gets a query for <see cref="PetShop.Core.Data.Inventory"/>.
        ''' </summary>
        ''' <param name="queryable">Query to append where clause.</param>
        ''' <param name="itemId">ItemId to search for.</param>
        ''' <param name="additionalValues">Additional values to search for.</param>
        ''' <returns>IQueryable with additional where clause.</returns>
        <System.Runtime.CompilerServices.Extension()> _
        Public Function ByItemId(ByVal queryable As IQueryable(Of PetShop.Core.Data.Inventory), ByVal itemId As String, ByVal ParamArray additionalValues As String()) As IQueryable(Of PetShop.Core.Data.Inventory)
            Dim values = New List(Of String)()
            values.Add(itemId)
        
            If additionalValues IsNot Nothing Then
                values.AddRange(additionalValues)
            End If
        
            If values.Count = 1 Then
                Return queryable.ByItemId(values(0))
            End If
        
            Return queryable.ByItemId(values)
        End Function
        
        ''' <summary>
        ''' Gets a query for <see cref="PetShop.Core.Data.Inventory"/>.
        ''' </summary>
        ''' <param name="queryable">Query to append where clause.</param>
        ''' <param name="values">The values to search for.</param>
        ''' <returns>IQueryable with additional where clause.</returns>
        <System.Runtime.CompilerServices.Extension()> _
        Public Function ByItemId(ByVal queryable As IQueryable(Of PetShop.Core.Data.Inventory), ByVal values As IEnumerable(Of String)) As IQueryable(Of PetShop.Core.Data.Inventory)
                Return queryable.Where(Function(i) values.Contains(i.ItemId))
        End Function

        ''' <summary>
        ''' Gets a query for <see cref="PetShop.Core.Data.Inventory"/>.
        ''' </summary>
        ''' <param name="queryable">Query to append where clause.</param>
        ''' <param name="itemId">ItemId to search for.</param>
        ''' <param name="containment">The containment operator.</param>
        ''' <returns>IQueryable with additional where clause.</returns>
        <System.Runtime.CompilerServices.Extension()> _
        Public Function ByItemId(ByVal queryable As IQueryable(Of PetShop.Core.Data.Inventory), ByVal itemId As String, ByVal containment As ContainmentOperator) As IQueryable(Of PetShop.Core.Data.Inventory)
            If itemId Is Nothing AndAlso containment <> ContainmentOperator.Equals AndAlso containment <> ContainmentOperator.NotEquals Then
                Throw New ArgumentNullException("itemId", "Parameter 'itemId' cannot be null with the specified ContainmentOperator.  Parameter 'containmentOperator' must be ContainmentOperator.Equals or ContainmentOperator.NotEquals to support null.")
            End If
            
            Select Case containment
                Case ContainmentOperator.Contains
                    Return queryable.Where(Function(i) i.ItemId.Contains(itemId))
                Case ContainmentOperator.StartsWith
                    Return queryable.Where(Function(i) i.ItemId.StartsWith(itemId))
                Case ContainmentOperator.EndsWith
                    Return queryable.Where(Function(i) i.ItemId.EndsWith(itemId))
                Case ContainmentOperator.NotContains
                    Return queryable.Where(Function(i) i.ItemId.Contains(itemId) = False)
                Case ContainmentOperator.NotEquals
                    Return queryable.Where(Function(i) i.ItemId <> itemId)
                Case Else
                    Return queryable.Where(Function(i) i.ItemId = itemId)
            End Select
        End Function
        

        ''' <summary>
        ''' Gets a query for <see cref="PetShop.Core.Data.Inventory"/>.
        ''' </summary>
        ''' <param name="queryable">Query to append where clause.</param>
        ''' <param name="qty">Qty to search for.</param>
        ''' <returns>IQueryable with additional where clause.</returns>
        <System.Runtime.CompilerServices.Extension()> _
        Public Function ByQty(ByVal queryable As IQueryable(Of PetShop.Core.Data.Inventory), ByVal qty As Integer) As IQueryable(Of PetShop.Core.Data.Inventory)
            Return queryable.Where(Function(i)i.Qty = qty)
        End Function
        
        ''' <summary>
        ''' Gets a query for <see cref="PetShop.Core.Data.Inventory"/>.
        ''' </summary>
        ''' <param name="queryable">Query to append where clause.</param>
        ''' <param name="qty">Qty to search for.</param>
        ''' <param name="additionalValues">Additional values to search for.</param>
        ''' <returns>IQueryable with additional where clause.</returns>
        <System.Runtime.CompilerServices.Extension()> _
        Public Function ByQty(ByVal queryable As IQueryable(Of PetShop.Core.Data.Inventory), ByVal qty As Integer, ByVal ParamArray additionalValues As Integer()) As IQueryable(Of PetShop.Core.Data.Inventory)
            Dim values = New List(Of Integer)()
            values.Add(qty)
        
            If additionalValues IsNot Nothing Then
                values.AddRange(additionalValues)
            End If
        
            If values.Count = 1 Then
                Return queryable.ByQty(values(0))
            End If
        
            Return queryable.ByQty(values)
        End Function
        
        ''' <summary>
        ''' Gets a query for <see cref="PetShop.Core.Data.Inventory"/>.
        ''' </summary>
        ''' <param name="queryable">Query to append where clause.</param>
        ''' <param name="values">The values to search for.</param>
        ''' <returns>IQueryable with additional where clause.</returns>
        <System.Runtime.CompilerServices.Extension()> _
        Public Function ByQty(ByVal queryable As IQueryable(Of PetShop.Core.Data.Inventory), ByVal values As IEnumerable(Of Integer)) As IQueryable(Of PetShop.Core.Data.Inventory)
                Return queryable.Where(Function(i) values.Contains(i.Qty))
        End Function

        ''' <summary>
        ''' Gets a query for <see cref="PetShop.Core.Data.Inventory"/>.
        ''' </summary>
        ''' <param name="queryable">Query to append where clause.</param>
        ''' <param name="qty">Qty to search for.</param>
        ''' <param name="comparison">The comparison operator.</param>
        ''' <returns>IQueryable with additional where clause.</returns>
        <System.Runtime.CompilerServices.Extension()> _
        Public Function ByQty(ByVal queryable As IQueryable(Of PetShop.Core.Data.Inventory), ByVal qty As Integer, ByVal comparison As ComparisonOperator) As IQueryable(Of PetShop.Core.Data.Inventory)
            Select Case comparison
                Case ComparisonOperator.GreaterThan
                    Return queryable.Where(Function(i) qty > i.Qty)
                Case ComparisonOperator.GreaterThanOrEquals
                    Return queryable.Where(Function(i) qty >= i.Qty)
                Case ComparisonOperator.LessThan
                    Return queryable.Where(Function(i) qty < i.Qty)
                Case ComparisonOperator.LessThanOrEquals
                    Return queryable.Where(Function(i) qty <= i.Qty)
                Case ComparisonOperator.NotEquals
                    Return queryable.Where(Function(i) i.Qty <> qty)
                Case Else
                    Return queryable.Where(Function(i) i.Qty = qty)
            End Select
        End Function


        'Insert User Defined Extensions here.
        'Anything outside of this Region will be lost at regeneration
        #Region "User Extensions"


        #End Region

        #Region "Query"
        ''' <summary>
        ''' A private class for lazy loading static compiled queries.
        ''' </summary>
        Private Partial Class Query


            Friend Shared ReadOnly GetByKey As Func(Of PetshopDataContext, String, PetShop.Core.Data.Inventory) = _
                CompiledQuery.Compile( _
                    Function(db As PetshopDataContext , ByVal itemId As String) _
                        db.Inventory.FirstOrDefault(Function(i)i.ItemId = itemId))

            ' Add your compiled queries here.
            'Anything outside of this Region will be lost at regeneration
            #Region "User Queries"

            #End Region

        End Class
        #End Region
    End Module
End Namespace

