
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.Data.SqlTypes;
using System.Linq;
using System.Text;
using CodeSmith.Data;
using CodeSmith.Data.Rules;
using CodeSmith.Data.Rules.Assign;
using CodeSmith.Data.Rules.Validation;

namespace Petshop.Data
{
    /// <summary>
    /// The manager class for Product.
    /// </summary>
    public partial class ProductManager : EntityManagerBase<PetshopDataManager, Product>
    {
        /// <summary>
        /// Initializes the <see cref="ProductManager"/> class.
        /// </summary>
        static ProductManager()
        {
            RuleManager.AddShared<Product>(typeof(PetshopDataContext));
            AddRules();
        }

        /// <summary>
        /// Initializes the <see cref="ProductManager"/> class.
        /// </summary>
        /// <param name="manager">The current manager.</param>
        public ProductManager(PetshopDataManager manager) : base(manager)
        {
            OnCreated();
        }

        /// <summary>
        /// Gets the current context.
        /// </summary>
        protected PetshopDataContext Context
        {
            get { return Manager.Context; }
        }
        
        /// <summary>
        /// Gets the entity for this manager.
        /// </summary>
        protected Table<Product> Entity
        {
            get { return Manager.Context.Product; }
        }
        
        
        /// <summary>
        /// Creates the key for this entity.
        /// </summary>
        public static IEntityKey<string> CreateKey(string productId)
        {
            return new EntityKey<string>(productId);
        }
        
        /// <summary>
        /// Gets an entity by the primary key.
        /// </summary>
        /// <param name="key">The key for the entity.</param>
        /// <returns>
        /// An instance of the entity or null if not found.
        /// </returns>
        /// <remarks>
        /// This method is expecting key to be of type IEntityKey&lt;string&gt;.
        /// </remarks>
        /// <exception cref="ArgumentException">Thrown when key is not of type IEntityKey&lt;string&gt;.</exception>
        public override Product GetByKey(IEntityKey key)
        {
            if (key is IEntityKey<string>)
            {
                IEntityKey<string> entityKey = (IEntityKey<string>)key;
                return GetByKey(entityKey.Key);
            }
            else
            {
                throw new ArgumentException("Invalid key, expected key to be of type IEntityKey<string>");
            }
        }
        
        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public Product GetByKey(string productId)
        {
            if (Context.LoadOptions == null) 
                return Query.GetByKey.Invoke(Context, productId);
            else
                return Entity.FirstOrDefault(p => p.ProductId == productId);
        }
        /// <summary>
        /// Gets a query by an index.
        /// </summary>
        public IQueryable<Product> GetByName(string name)
        {
            if (Context.LoadOptions == null) 
                return Query.GetByName.Invoke(Context, name);
            else
                return Entity.Where(p => p.Name == name);
        }
        /// <summary>
        /// Gets a query by an index.
        /// </summary>
        public IQueryable<Product> GetByCategoryId(string categoryId)
        {
            if (Context.LoadOptions == null) 
                return Query.GetByCategoryId.Invoke(Context, categoryId);
            else
                return Entity.Where(p => p.CategoryId == categoryId);
        }
        /// <summary>
        /// Gets a query by an index.
        /// </summary>
        public IQueryable<Product> GetByCategoryIdName(string categoryId, string name)
        {
            if (Context.LoadOptions == null) 
                return Query.GetByCategoryIdName.Invoke(Context, categoryId, name);
            else
                return Entity.Where(p => p.CategoryId == categoryId 
					&& p.Name == name);
        }
        /// <summary>
        /// Gets a query by an index.
        /// </summary>
        public IQueryable<Product> GetByCategoryIdProductIdName(string categoryId, string productId, string name)
        {
            if (Context.LoadOptions == null) 
                return Query.GetByCategoryIdProductIdName.Invoke(Context, categoryId, productId, name);
            else
                return Entity.Where(p => p.CategoryId == categoryId 
					&& p.ProductId == productId 
					&& p.Name == name);
        }

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        static partial void AddRules();
        /// <summary>Called when the class is created.</summary>
        partial void OnCreated();
        #endregion
        
        #region Query
        /// <summary>
        /// A private class for lazy loading static compiled queries.
        /// </summary>
        private static partial class Query
        {

            internal static readonly Func<PetshopDataContext, string, Product> GetByKey = 
                CompiledQuery.Compile(
                    (PetshopDataContext db, string productId) => 
                        db.Product.FirstOrDefault(p => p.ProductId == productId));

            internal static readonly Func<PetshopDataContext, string, IQueryable<Product>> GetByName = 
                CompiledQuery.Compile(
                    (PetshopDataContext db, string name) => 
                        db.Product.Where(p => p.Name == name));

            internal static readonly Func<PetshopDataContext, string, IQueryable<Product>> GetByCategoryId = 
                CompiledQuery.Compile(
                    (PetshopDataContext db, string categoryId) => 
                        db.Product.Where(p => p.CategoryId == categoryId));

            internal static readonly Func<PetshopDataContext, string, string, IQueryable<Product>> GetByCategoryIdName = 
                CompiledQuery.Compile(
                    (PetshopDataContext db, string categoryId, string name) => 
                        db.Product.Where(p => p.CategoryId == categoryId 
							&& p.Name == name));

            internal static readonly Func<PetshopDataContext, string, string, string, IQueryable<Product>> GetByCategoryIdProductIdName = 
                CompiledQuery.Compile(
                    (PetshopDataContext db, string categoryId, string productId, string name) => 
                        db.Product.Where(p => p.CategoryId == categoryId 
							&& p.ProductId == productId 
							&& p.Name == name));

        }
        #endregion
    }
}

