//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Ugly.Data
{
    public partial class UglyContext
        : System.Data.Entity.DbContext
    {
        static UglyContext()
        {
            System.Data.Entity.Database.SetInitializer<UglyContext>(null);
        }

        public System.Data.Entity.DbSet<Ugly.Data.Entities.ContactImport> ContactImports { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.Department> Departments { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.Employee> Employees { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.Duplicate> Duplicates { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.EmployeeDepartment> EmployeeDepartments { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.GuidAuto> GuidAutos { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.Keyword> Keywords { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.Membership> Memberships { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.Object> Objects { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.OrderDocument> OrderDocuments { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.Provider> Providers { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.Query> Queries { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.Role> Roles { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.SqlType> SqlTypes { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.TableExample> TableExamples { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.Table1Test> Table1Tests { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.Template> Templates { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.TwoForeignKey> TwoForeignKeys { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.TwoKey> TwoKeys { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.User> Users { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.UserRole> UserRoles { get; set; }
        public System.Data.Entity.DbSet<Ugly.Data.Entities.Duplicate1> Duplicate1s { get; set; }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<System.Data.Entity.Infrastructure.IncludeMetadataConvention>();
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.ContactImportMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.DepartmentMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.EmployeeMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.DuplicateMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.EmployeeDepartmentMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.GuidAutoMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.KeywordMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.MembershipMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.ObjectMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.OrderDocumentMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.ProviderMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.QueryMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.RoleMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.SqlTypeMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.TableExampleMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.Table1TestMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.TemplateMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.TwoForeignKeyMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.TwoKeyMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.UserMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.UserRoleMap());
            modelBuilder.Configurations.Add(new Ugly.Data.Mapping.Duplicate1Map());

            InitializeMapping(modelBuilder);
        }
    }
}