//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated using CSLA 3.8.X CodeSmith Templates.
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'OrderStatus.cs'.
//
//     Template path: EditableRoot.Generated.cst
//     Template website: http://code.google.com/p/codesmith/
// </autogenerated>
//------------------------------------------------------------------------------
#region Using declarations

using System;

using Csla;
using Csla.Data;
using Csla.Validation;

#endregion

namespace PetShop.Business
{
    [Serializable]
    public partial class OrderStatus : BusinessBase< OrderStatus >
    {
        #region Contructor(s)

        private OrderStatus()
        { /* Require use of factory methods */ }

        private OrderStatus(System.Int32 orderId, System.Int32 lineNum)
        {
            OrderId = orderId;
            LineNum = lineNum;
        }

        internal OrderStatus(SafeDataReader reader)
        {
            Map(reader);
        }
        #endregion

        #region Validation Rules

        protected override void AddBusinessRules()
        {
            if(AddBusinessValidationRules())
                return;

            ValidationRules.AddRule(CommonRules.StringRequired, _statusProperty);
            ValidationRules.AddRule(CommonRules.StringMaxLength, new CommonRules.MaxLengthRuleArgs(_statusProperty, 2));
        }

        #endregion

        #region Properties

        private static readonly PropertyInfo< System.Int32 > _orderIdProperty = RegisterProperty< System.Int32 >(p => p.OrderId);
		[System.ComponentModel.DataObjectField(true, false)]
        public System.Int32 OrderId
        {
            get { return GetProperty(_orderIdProperty); }
            set{ SetProperty(_orderIdProperty, value); }
        }

        private static readonly PropertyInfo< System.Int32 > _lineNumProperty = RegisterProperty< System.Int32 >(p => p.LineNum);
		[System.ComponentModel.DataObjectField(true, false)]
        public System.Int32 LineNum
        {
            get { return GetProperty(_lineNumProperty); }
            set{ SetProperty(_lineNumProperty, value); }
        }

        private static readonly PropertyInfo< System.DateTime > _timestampProperty = RegisterProperty< System.DateTime >(p => p.Timestamp);
        public System.DateTime Timestamp
        {
            get { return GetProperty(_timestampProperty); }
            set{ SetProperty(_timestampProperty, value); }
        }

        private static readonly PropertyInfo< System.String > _statusProperty = RegisterProperty< System.String >(p => p.Status);
        public System.String Status
        {
            get { return GetProperty(_statusProperty); }
            set{ SetProperty(_statusProperty, value); }
        }

        //AssociatedManyToOne
        private static readonly PropertyInfo< Order > _orderMemberProperty = RegisterProperty< Order >(p => p.OrderMember, RelationshipTypes.LazyLoad);
        public Order OrderMember
        {
            get
            {
                if(!FieldManager.FieldExists(_orderMemberProperty))
                {
                    if(IsNew)
                        LoadProperty(_orderMemberProperty, PetShop.Business.Order.NewOrder());
                    else
                        LoadProperty(_orderMemberProperty, PetShop.Business.Order.GetByOrderId(OrderId));
                }

                return GetProperty(_orderMemberProperty); 
            }
        }


        #endregion


        #region Factory Methods 

        public static OrderStatus NewOrderStatus()
        {
            return DataPortal.Create< OrderStatus >();
        }

        public static OrderStatus GetByOrderIdLineNum(System.Int32 orderId, System.Int32 lineNum)
        {
            return DataPortal.Fetch< OrderStatus >(
                new OrderStatusCriteria{OrderId = orderId, LineNum = lineNum});
        }

        public static OrderStatus GetByOrderId(System.Int32 orderId)
        {
            return DataPortal.Fetch< OrderStatus >(
                new OrderStatusCriteria{OrderId = orderId});
        }

        public static void DeleteOrderStatus(System.Int32 orderId, System.Int32 lineNum)
        {
            DataPortal.Delete(new OrderStatusCriteria{OrderId = orderId, LineNum = lineNum});
        }

        #endregion

        #region Protected Overriden Method(s)

        // NOTE: This is needed for Composite Keys. 
        private readonly Guid _guidID = Guid.NewGuid();
        protected override object GetIdValue()
        {
            return _guidID;
        }

        #endregion
    }
}