//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated using CodeSmith: v5.2.2, CSLA Templates: v3.0.0.0, CSLA Framework: v4.0.0.
//     Changes to this file will be lost after each regeneration.
//
//     Template: IGeneratedCriteria.cst
//     Template website: http://code.google.com/p/codesmith/
// </autogenerated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace PetShop.Business
{
    public interface IGeneratedCriteria
    {
        Dictionary<string, object> StateBag { get; }
        string TableFullName { get; }
    }
}