'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a CodeSmith Template.
'
'     DO Not MODIfY contents of this file. Changes to this
'     file will be lost if the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Diagnostics
Imports System.Runtime.Serialization
Imports System.ComponentModel.DataAnnotations
Imports System.Data.Services.Common

Namespace Petshop.Data
    ''' <summary>
    ''' The class representing the dbo.Orders table.
    ''' </summary>
    <Table(Name:="dbo.Orders")> _
    <DataContract(IsReference:=True)> _
    <ScaffoldTable(True)> _
    <MetadataType(GetType(Orders.Metadata))> _
	<DataServiceKey("OrderId")> _
    public Partial Class Orders
        Inherits LinqEntityBase
        
        #Region "Default Constructor"
        ''' <summary>
        ''' Initializes a new instance of the <see cref="Orders"/> class.
        ''' </summary>
        <DebuggerNonUserCodeAttribute()> _
        public  Sub New()
              OnCreated()
            Initialize()
        End Sub
        
        Private Sub Initialize()
            _lineItemList = New EntitySet(Of LineItem)( _
                New System.Action(Of LineItem)(AddressOf Me.Attach_LineItemList), _
                New System.Action(Of LineItem)(AddressOf Me.Detach_LineItemList))
            _orderStatusList = New EntitySet(Of OrderStatus)( _
                New System.Action(Of OrderStatus)(AddressOf Me.Attach_OrderStatusList), _
                New System.Action(Of OrderStatus)(AddressOf Me.Detach_OrderStatusList))
        End Sub
        #End Region

        #Region "Column Mapped Properties"
        
        Private _orderId As Integer = Nothing

        ''' <summary>
        ''' Gets the OrderId column value.
        ''' </summary>
        <Column(Name:="OrderId", Storage:="_orderId", DbType:="int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true, CanBeNull:=false)> _
        <DataMember(Order:=1)> _
        public Property OrderId As Integer
            Get 
                return _orderId 
            End Get
            Set
                If  Not _orderId.Equals(value) Then
                    OnOrderIdChanging(value)
                    OnPropertyChanging("OrderId")
                    _orderId = value
                    OnPropertyChanged("OrderId")
                    OnOrderIdChanged()
                End If
            End Set
        End Property
        
        Private _userId As String

        ''' <summary>
        ''' Gets or sets the UserId column value.
        ''' </summary>
        <Column(Name:="UserId", Storage:="_userId", DbType:="varchar(20) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=2)> _
        public Property UserId As String
            Get 
                return _userId 
            End Get
            Set
                If String.IsNullOrEmpty(_userId) OrElse  Not _userId.Equals(value) Then
                    OnUserIdChanging(value)
                    OnPropertyChanging("UserId")
                    _userId = value
                    OnPropertyChanged("UserId")
                    OnUserIdChanged()
                End If
            End Set
        End Property
        
        Private _orderDate As Date

        ''' <summary>
        ''' Gets or sets the OrderDate column value.
        ''' </summary>
        <Column(Name:="OrderDate", Storage:="_orderDate", DbType:="datetime NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=3)> _
        public Property OrderDate As Date
            Get 
                return _orderDate 
            End Get
            Set
                If  Not _orderDate.Equals(value) Then
                    OnOrderDateChanging(value)
                    OnPropertyChanging("OrderDate")
                    _orderDate = value
                    OnPropertyChanged("OrderDate")
                    OnOrderDateChanged()
                End If
            End Set
        End Property
        
        Private _shipAddr1 As String

        ''' <summary>
        ''' Gets or sets the ShipAddr1 column value.
        ''' </summary>
        <Column(Name:="ShipAddr1", Storage:="_shipAddr1", DbType:="varchar(80) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=4)> _
        public Property ShipAddr1 As String
            Get 
                return _shipAddr1 
            End Get
            Set
                If String.IsNullOrEmpty(_shipAddr1) OrElse  Not _shipAddr1.Equals(value) Then
                    OnShipAddr1Changing(value)
                    OnPropertyChanging("ShipAddr1")
                    _shipAddr1 = value
                    OnPropertyChanged("ShipAddr1")
                    OnShipAddr1Changed()
                End If
            End Set
        End Property
        
        Private _shipAddr2 As String

        ''' <summary>
        ''' Gets or sets the ShipAddr2 column value.
        ''' </summary>
        <Column(Name:="ShipAddr2", Storage:="_shipAddr2", DbType:="varchar(80)")> _
        <DataMember(Order:=5)> _
        public Property ShipAddr2 As String
            Get 
                return _shipAddr2 
            End Get
            Set
                If String.IsNullOrEmpty(_shipAddr2) OrElse  Not _shipAddr2.Equals(value) Then
                    OnShipAddr2Changing(value)
                    OnPropertyChanging("ShipAddr2")
                    _shipAddr2 = value
                    OnPropertyChanged("ShipAddr2")
                    OnShipAddr2Changed()
                End If
            End Set
        End Property
        
        Private _shipCity As String

        ''' <summary>
        ''' Gets or sets the ShipCity column value.
        ''' </summary>
        <Column(Name:="ShipCity", Storage:="_shipCity", DbType:="varchar(80) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=6)> _
        public Property ShipCity As String
            Get 
                return _shipCity 
            End Get
            Set
                If String.IsNullOrEmpty(_shipCity) OrElse  Not _shipCity.Equals(value) Then
                    OnShipCityChanging(value)
                    OnPropertyChanging("ShipCity")
                    _shipCity = value
                    OnPropertyChanged("ShipCity")
                    OnShipCityChanged()
                End If
            End Set
        End Property
        
        Private _shipState As String

        ''' <summary>
        ''' Gets or sets the ShipState column value.
        ''' </summary>
        <Column(Name:="ShipState", Storage:="_shipState", DbType:="varchar(80) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=7)> _
        public Property ShipState As String
            Get 
                return _shipState 
            End Get
            Set
                If String.IsNullOrEmpty(_shipState) OrElse  Not _shipState.Equals(value) Then
                    OnShipStateChanging(value)
                    OnPropertyChanging("ShipState")
                    _shipState = value
                    OnPropertyChanged("ShipState")
                    OnShipStateChanged()
                End If
            End Set
        End Property
        
        Private _shipZip As String

        ''' <summary>
        ''' Gets or sets the ShipZip column value.
        ''' </summary>
        <Column(Name:="ShipZip", Storage:="_shipZip", DbType:="varchar(20) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=8)> _
        public Property ShipZip As String
            Get 
                return _shipZip 
            End Get
            Set
                If String.IsNullOrEmpty(_shipZip) OrElse  Not _shipZip.Equals(value) Then
                    OnShipZipChanging(value)
                    OnPropertyChanging("ShipZip")
                    _shipZip = value
                    OnPropertyChanged("ShipZip")
                    OnShipZipChanged()
                End If
            End Set
        End Property
        
        Private _shipCountry As String

        ''' <summary>
        ''' Gets or sets the ShipCountry column value.
        ''' </summary>
        <Column(Name:="ShipCountry", Storage:="_shipCountry", DbType:="varchar(20) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=9)> _
        public Property ShipCountry As String
            Get 
                return _shipCountry 
            End Get
            Set
                If String.IsNullOrEmpty(_shipCountry) OrElse  Not _shipCountry.Equals(value) Then
                    OnShipCountryChanging(value)
                    OnPropertyChanging("ShipCountry")
                    _shipCountry = value
                    OnPropertyChanged("ShipCountry")
                    OnShipCountryChanged()
                End If
            End Set
        End Property
        
        Private _billAddr1 As String

        ''' <summary>
        ''' Gets or sets the BillAddr1 column value.
        ''' </summary>
        <Column(Name:="BillAddr1", Storage:="_billAddr1", DbType:="varchar(80) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=10)> _
        public Property BillAddr1 As String
            Get 
                return _billAddr1 
            End Get
            Set
                If String.IsNullOrEmpty(_billAddr1) OrElse  Not _billAddr1.Equals(value) Then
                    OnBillAddr1Changing(value)
                    OnPropertyChanging("BillAddr1")
                    _billAddr1 = value
                    OnPropertyChanged("BillAddr1")
                    OnBillAddr1Changed()
                End If
            End Set
        End Property
        
        Private _billAddr2 As String

        ''' <summary>
        ''' Gets or sets the BillAddr2 column value.
        ''' </summary>
        <Column(Name:="BillAddr2", Storage:="_billAddr2", DbType:="varchar(80)")> _
        <DataMember(Order:=11)> _
        public Property BillAddr2 As String
            Get 
                return _billAddr2 
            End Get
            Set
                If String.IsNullOrEmpty(_billAddr2) OrElse  Not _billAddr2.Equals(value) Then
                    OnBillAddr2Changing(value)
                    OnPropertyChanging("BillAddr2")
                    _billAddr2 = value
                    OnPropertyChanged("BillAddr2")
                    OnBillAddr2Changed()
                End If
            End Set
        End Property
        
        Private _billCity As String

        ''' <summary>
        ''' Gets or sets the BillCity column value.
        ''' </summary>
        <Column(Name:="BillCity", Storage:="_billCity", DbType:="varchar(80) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=12)> _
        public Property BillCity As String
            Get 
                return _billCity 
            End Get
            Set
                If String.IsNullOrEmpty(_billCity) OrElse  Not _billCity.Equals(value) Then
                    OnBillCityChanging(value)
                    OnPropertyChanging("BillCity")
                    _billCity = value
                    OnPropertyChanged("BillCity")
                    OnBillCityChanged()
                End If
            End Set
        End Property
        
        Private _billState As String

        ''' <summary>
        ''' Gets or sets the BillState column value.
        ''' </summary>
        <Column(Name:="BillState", Storage:="_billState", DbType:="varchar(80) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=13)> _
        public Property BillState As String
            Get 
                return _billState 
            End Get
            Set
                If String.IsNullOrEmpty(_billState) OrElse  Not _billState.Equals(value) Then
                    OnBillStateChanging(value)
                    OnPropertyChanging("BillState")
                    _billState = value
                    OnPropertyChanged("BillState")
                    OnBillStateChanged()
                End If
            End Set
        End Property
        
        Private _billZip As String

        ''' <summary>
        ''' Gets or sets the BillZip column value.
        ''' </summary>
        <Column(Name:="BillZip", Storage:="_billZip", DbType:="varchar(20) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=14)> _
        public Property BillZip As String
            Get 
                return _billZip 
            End Get
            Set
                If String.IsNullOrEmpty(_billZip) OrElse  Not _billZip.Equals(value) Then
                    OnBillZipChanging(value)
                    OnPropertyChanging("BillZip")
                    _billZip = value
                    OnPropertyChanged("BillZip")
                    OnBillZipChanged()
                End If
            End Set
        End Property
        
        Private _billCountry As String

        ''' <summary>
        ''' Gets or sets the BillCountry column value.
        ''' </summary>
        <Column(Name:="BillCountry", Storage:="_billCountry", DbType:="varchar(20) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=15)> _
        public Property BillCountry As String
            Get 
                return _billCountry 
            End Get
            Set
                If String.IsNullOrEmpty(_billCountry) OrElse  Not _billCountry.Equals(value) Then
                    OnBillCountryChanging(value)
                    OnPropertyChanging("BillCountry")
                    _billCountry = value
                    OnPropertyChanged("BillCountry")
                    OnBillCountryChanged()
                End If
            End Set
        End Property
        
        Private _courier As String

        ''' <summary>
        ''' Gets or sets the Courier column value.
        ''' </summary>
        <Column(Name:="Courier", Storage:="_courier", DbType:="varchar(80) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=16)> _
        public Property Courier As String
            Get 
                return _courier 
            End Get
            Set
                If String.IsNullOrEmpty(_courier) OrElse  Not _courier.Equals(value) Then
                    OnCourierChanging(value)
                    OnPropertyChanging("Courier")
                    _courier = value
                    OnPropertyChanged("Courier")
                    OnCourierChanged()
                End If
            End Set
        End Property
        
        Private _totalPrice As Decimal

        ''' <summary>
        ''' Gets or sets the TotalPrice column value.
        ''' </summary>
        <Column(Name:="TotalPrice", Storage:="_totalPrice", DbType:="decimal(10,2) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=17)> _
        public Property TotalPrice As Decimal
            Get 
                return _totalPrice 
            End Get
            Set
                If  Not _totalPrice.Equals(value) Then
                    OnTotalPriceChanging(value)
                    OnPropertyChanging("TotalPrice")
                    _totalPrice = value
                    OnPropertyChanged("TotalPrice")
                    OnTotalPriceChanged()
                End If
            End Set
        End Property
        
        Private _billToFirstName As String

        ''' <summary>
        ''' Gets or sets the BillToFirstName column value.
        ''' </summary>
        <Column(Name:="BillToFirstName", Storage:="_billToFirstName", DbType:="varchar(80) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=18)> _
        public Property BillToFirstName As String
            Get 
                return _billToFirstName 
            End Get
            Set
                If String.IsNullOrEmpty(_billToFirstName) OrElse  Not _billToFirstName.Equals(value) Then
                    OnBillToFirstNameChanging(value)
                    OnPropertyChanging("BillToFirstName")
                    _billToFirstName = value
                    OnPropertyChanged("BillToFirstName")
                    OnBillToFirstNameChanged()
                End If
            End Set
        End Property
        
        Private _billToLastName As String

        ''' <summary>
        ''' Gets or sets the BillToLastName column value.
        ''' </summary>
        <Column(Name:="BillToLastName", Storage:="_billToLastName", DbType:="varchar(80) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=19)> _
        public Property BillToLastName As String
            Get 
                return _billToLastName 
            End Get
            Set
                If String.IsNullOrEmpty(_billToLastName) OrElse  Not _billToLastName.Equals(value) Then
                    OnBillToLastNameChanging(value)
                    OnPropertyChanging("BillToLastName")
                    _billToLastName = value
                    OnPropertyChanged("BillToLastName")
                    OnBillToLastNameChanged()
                End If
            End Set
        End Property
        
        Private _shipToFirstName As String

        ''' <summary>
        ''' Gets or sets the ShipToFirstName column value.
        ''' </summary>
        <Column(Name:="ShipToFirstName", Storage:="_shipToFirstName", DbType:="varchar(80) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=20)> _
        public Property ShipToFirstName As String
            Get 
                return _shipToFirstName 
            End Get
            Set
                If String.IsNullOrEmpty(_shipToFirstName) OrElse  Not _shipToFirstName.Equals(value) Then
                    OnShipToFirstNameChanging(value)
                    OnPropertyChanging("ShipToFirstName")
                    _shipToFirstName = value
                    OnPropertyChanged("ShipToFirstName")
                    OnShipToFirstNameChanged()
                End If
            End Set
        End Property
        
        Private _shipToLastName As String

        ''' <summary>
        ''' Gets or sets the ShipToLastName column value.
        ''' </summary>
        <Column(Name:="ShipToLastName", Storage:="_shipToLastName", DbType:="varchar(80) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=21)> _
        public Property ShipToLastName As String
            Get 
                return _shipToLastName 
            End Get
            Set
                If String.IsNullOrEmpty(_shipToLastName) OrElse  Not _shipToLastName.Equals(value) Then
                    OnShipToLastNameChanging(value)
                    OnPropertyChanging("ShipToLastName")
                    _shipToLastName = value
                    OnPropertyChanged("ShipToLastName")
                    OnShipToLastNameChanged()
                End If
            End Set
        End Property
        
        Private _authorizationNumber As Integer

        ''' <summary>
        ''' Gets or sets the AuthorizationNumber column value.
        ''' </summary>
        <Column(Name:="AuthorizationNumber", Storage:="_authorizationNumber", DbType:="int NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=22)> _
        public Property AuthorizationNumber As Integer
            Get 
                return _authorizationNumber 
            End Get
            Set
                If  Not _authorizationNumber.Equals(value) Then
                    OnAuthorizationNumberChanging(value)
                    OnPropertyChanging("AuthorizationNumber")
                    _authorizationNumber = value
                    OnPropertyChanged("AuthorizationNumber")
                    OnAuthorizationNumberChanged()
                End If
            End Set
        End Property
        
        Private _locale As String

        ''' <summary>
        ''' Gets or sets the Locale column value.
        ''' </summary>
        <Column(Name:="Locale", Storage:="_locale", DbType:="varchar(20) NOT NULL", CanBeNull:=false)> _
        <DataMember(Order:=23)> _
        public Property Locale As String
            Get 
                return _locale 
            End Get
            Set
                If String.IsNullOrEmpty(_locale) OrElse  Not _locale.Equals(value) Then
                    OnLocaleChanging(value)
                    OnPropertyChanging("Locale")
                    _locale = value
                    OnPropertyChanged("Locale")
                    OnLocaleChanged()
                End If
            End Set
        End Property
        #End Region
        
        #Region "Association Mapped Properties"
        
        
        Private _lineItemList As EntitySet(Of LineItem)
        
        ''' <summary>
        ''' Gets or sets the LineItem association.
        ''' </summary>
        <Association(Name:="Orders_LineItem", Storage:="_lineItemList", ThisKey:="OrderId", OtherKey:="OrderId")> _
        <DataMember()> _
        public Property LineItemList As EntitySet(Of LineItem)
            Get
                If (serializing AndAlso Not _lineItemList.HasLoadedOrAssignedValues) Then
                    Return Nothing
                End If
                return _lineItemList
            End Get
            Set
                _lineItemList.Assign(value)
            End Set
        End Property
        
        <DebuggerNonUserCodeAttribute()> _
        Private Sub Attach_LineItemList(ByVal entity As LineItem)
            OnPropertyChanging(Nothing)
            entity.Orders = Me
            OnPropertyChanged(Nothing)
        End Sub
        
        <DebuggerNonUserCodeAttribute()> _
        Private Sub Detach_LineItemList(ByVal entity As LineItem)
            OnPropertyChanging(Nothing)
            entity.Orders = Nothing
            OnPropertyChanged(Nothing)
        End Sub
        
        Private _orderStatusList As EntitySet(Of OrderStatus)
        
        ''' <summary>
        ''' Gets or sets the OrderStatus association.
        ''' </summary>
        <Association(Name:="Orders_OrderStatus", Storage:="_orderStatusList", ThisKey:="OrderId", OtherKey:="OrderId")> _
        <DataMember()> _
        public Property OrderStatusList As EntitySet(Of OrderStatus)
            Get
                If (serializing AndAlso Not _orderStatusList.HasLoadedOrAssignedValues) Then
                    Return Nothing
                End If
                return _orderStatusList
            End Get
            Set
                _orderStatusList.Assign(value)
            End Set
        End Property
        
        <DebuggerNonUserCodeAttribute()> _
        Private Sub Attach_OrderStatusList(ByVal entity As OrderStatus)
            OnPropertyChanging(Nothing)
            entity.Orders = Me
            OnPropertyChanged(Nothing)
        End Sub
        
        <DebuggerNonUserCodeAttribute()> _
        Private Sub Detach_OrderStatusList(ByVal entity As OrderStatus)
            OnPropertyChanging(Nothing)
            entity.Orders = Nothing
            OnPropertyChanged(Nothing)
        End Sub
           #End Region
        
        #Region "Extensibility Method Definitions"
        ''' <summary>Called when this instance is loaded.</summary>
        Private Partial Sub OnLoaded()
        End Sub
        ''' <summary>Called when this instance is being saved.</summary>
        Private Partial Sub OnValidate(ByVal action As ChangeAction)
        End Sub
        ''' <summary>Called when this instance is created.</summary>
        Private Partial Sub OnCreated()
        End Sub
        ''' <summary>Called when OrderId is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnOrderIdChanging(ByVal value As Integer)
        End Sub
        ''' <summary>Called after OrderId has Changed.</summary>
        Private Partial Sub OnOrderIdChanged()
        End Sub
        ''' <summary>Called when UserId is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnUserIdChanging(ByVal value As String)
        End Sub
        ''' <summary>Called after UserId has Changed.</summary>
        Private Partial Sub OnUserIdChanged()
        End Sub
        ''' <summary>Called when OrderDate is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnOrderDateChanging(ByVal value As Date)
        End Sub
        ''' <summary>Called after OrderDate has Changed.</summary>
        Private Partial Sub OnOrderDateChanged()
        End Sub
        ''' <summary>Called when ShipAddr1 is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnShipAddr1Changing(ByVal value As String)
        End Sub
        ''' <summary>Called after ShipAddr1 has Changed.</summary>
        Private Partial Sub OnShipAddr1Changed()
        End Sub
        ''' <summary>Called when ShipAddr2 is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnShipAddr2Changing(ByVal value As String)
        End Sub
        ''' <summary>Called after ShipAddr2 has Changed.</summary>
        Private Partial Sub OnShipAddr2Changed()
        End Sub
        ''' <summary>Called when ShipCity is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnShipCityChanging(ByVal value As String)
        End Sub
        ''' <summary>Called after ShipCity has Changed.</summary>
        Private Partial Sub OnShipCityChanged()
        End Sub
        ''' <summary>Called when ShipState is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnShipStateChanging(ByVal value As String)
        End Sub
        ''' <summary>Called after ShipState has Changed.</summary>
        Private Partial Sub OnShipStateChanged()
        End Sub
        ''' <summary>Called when ShipZip is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnShipZipChanging(ByVal value As String)
        End Sub
        ''' <summary>Called after ShipZip has Changed.</summary>
        Private Partial Sub OnShipZipChanged()
        End Sub
        ''' <summary>Called when ShipCountry is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnShipCountryChanging(ByVal value As String)
        End Sub
        ''' <summary>Called after ShipCountry has Changed.</summary>
        Private Partial Sub OnShipCountryChanged()
        End Sub
        ''' <summary>Called when BillAddr1 is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnBillAddr1Changing(ByVal value As String)
        End Sub
        ''' <summary>Called after BillAddr1 has Changed.</summary>
        Private Partial Sub OnBillAddr1Changed()
        End Sub
        ''' <summary>Called when BillAddr2 is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnBillAddr2Changing(ByVal value As String)
        End Sub
        ''' <summary>Called after BillAddr2 has Changed.</summary>
        Private Partial Sub OnBillAddr2Changed()
        End Sub
        ''' <summary>Called when BillCity is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnBillCityChanging(ByVal value As String)
        End Sub
        ''' <summary>Called after BillCity has Changed.</summary>
        Private Partial Sub OnBillCityChanged()
        End Sub
        ''' <summary>Called when BillState is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnBillStateChanging(ByVal value As String)
        End Sub
        ''' <summary>Called after BillState has Changed.</summary>
        Private Partial Sub OnBillStateChanged()
        End Sub
        ''' <summary>Called when BillZip is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnBillZipChanging(ByVal value As String)
        End Sub
        ''' <summary>Called after BillZip has Changed.</summary>
        Private Partial Sub OnBillZipChanged()
        End Sub
        ''' <summary>Called when BillCountry is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnBillCountryChanging(ByVal value As String)
        End Sub
        ''' <summary>Called after BillCountry has Changed.</summary>
        Private Partial Sub OnBillCountryChanged()
        End Sub
        ''' <summary>Called when Courier is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnCourierChanging(ByVal value As String)
        End Sub
        ''' <summary>Called after Courier has Changed.</summary>
        Private Partial Sub OnCourierChanged()
        End Sub
        ''' <summary>Called when TotalPrice is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnTotalPriceChanging(ByVal value As Decimal)
        End Sub
        ''' <summary>Called after TotalPrice has Changed.</summary>
        Private Partial Sub OnTotalPriceChanged()
        End Sub
        ''' <summary>Called when BillToFirstName is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnBillToFirstNameChanging(ByVal value As String)
        End Sub
        ''' <summary>Called after BillToFirstName has Changed.</summary>
        Private Partial Sub OnBillToFirstNameChanged()
        End Sub
        ''' <summary>Called when BillToLastName is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnBillToLastNameChanging(ByVal value As String)
        End Sub
        ''' <summary>Called after BillToLastName has Changed.</summary>
        Private Partial Sub OnBillToLastNameChanged()
        End Sub
        ''' <summary>Called when ShipToFirstName is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnShipToFirstNameChanging(ByVal value As String)
        End Sub
        ''' <summary>Called after ShipToFirstName has Changed.</summary>
        Private Partial Sub OnShipToFirstNameChanged()
        End Sub
        ''' <summary>Called when ShipToLastName is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnShipToLastNameChanging(ByVal value As String)
        End Sub
        ''' <summary>Called after ShipToLastName has Changed.</summary>
        Private Partial Sub OnShipToLastNameChanged()
        End Sub
        ''' <summary>Called when AuthorizationNumber is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnAuthorizationNumberChanging(ByVal value As Integer)
        End Sub
        ''' <summary>Called after AuthorizationNumber has Changed.</summary>
        Private Partial Sub OnAuthorizationNumberChanged()
        End Sub
        ''' <summary>Called when Locale is changing.</summary>
        ''' <param name="value">The new value.</param>
        Private Partial Sub OnLocaleChanging(ByVal value As String)
        End Sub
        ''' <summary>Called after Locale has Changed.</summary>
        Private Partial Sub OnLocaleChanged()
        End Sub
        #End Region
        
        
        #Region "Serialization"
        
        Private Serializing As Boolean
        
        <OnSerializing(), _
         EditorBrowsableAttribute(EditorBrowsableState.Never)> _
        Public Sub OnSerializing(ByVal context As StreamingContext)
            serializing = True
        End Sub
        
        <OnSerialized(), _
         EditorBrowsableAttribute(EditorBrowsableState.Never)> _
        Public Sub OnSerialized(ByVal context As StreamingContext)
            serializing = False
        End Sub
        
        <OnDeserializing(), _
         EditorBrowsableAttribute(EditorBrowsableState.Never)> _
        Public Sub OnDeserializing(ByVal context As StreamingContext)
            Initialize
        End Sub
        
        #End Region
    
    End Class
End Namespace

