
/****** Object:  Procedure [dbo].[aposa_GetUserData]    Script Date: 04/17/2007 10:00:51 AM ******/
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[aposa_GetUserData]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[aposa_GetUserData]
GO

/*********************************************************************************************
 
 Created By: This code was generated by APOSA CodeSmith Domain Object Template.
 Date:    04/17/2007
 Time:    10:00 AM
 Version: 4.0.0.0

 Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

 Procedure Name: [dbo].[aposa_GetUserData]
 
 Description: User Table
 
 Parameters: 
		@UserID int

       
--region RevisionLog
***************************************  Revision Log  ***************************************
 
Version   Date        Revised By       Description / WO#
--------  ----------  ---------------  -------------------------------------------------------
   
**********************************************************************************************/
--endregion
CREATE PROCEDURE [dbo].[aposa_GetUserData]
	@UserID int


AS

SET NOCOUNT ON

SELECT
		[UserID] AS 'UserID',
		[UserName] AS 'UserName',
		[DateCreated] AS 'DateCreated',
		[IsActive] AS 'IsActive',
		[Random Column 1] AS 'RandomColumn1',
		[Random_Column2] AS 'RandomColumn2'

FROM
	[dbo].[User]
WHERE
		[UserID] = @UserID


--region [dbo].[aposa_GetUserData]
------------------------------------------------------------------------------------------------------------------------");
-- Generated By:   cl1 using CodeSmith 4.0.0.0
-- Template:       SelectByPrimaryKeyStoredProcedure.cst
-- Procedure Name: [dbo].[aposa_GetUserData]
-- Date Generated: Tuesday, April 17, 2007
------------------------------------------------------------------------------------------------------------------------");
--endregion

