//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//
//     To make updates to Enums, please use the *.Enum.xml
//     file, hidded behind the *.dbml file.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Tester.Data
{
    [DataContract]
    public enum TagEnum : byte
    {
        [EnumMember]
        User = 1,
        [EnumMember]
        System = 2
    }
    
}
