#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using Petshop.Data;

namespace Petshop.Data.Entities
{
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.Diagnostics.DebuggerDisplay("OrderId: {OrderId}, UserId: {UserId}, OrderDate: {OrderDate}, ShipAddr1: {ShipAddr1}, ShipCity: {ShipCity}, ShipState: {ShipState}, ShipZip: {ShipZip}, ShipCountry: {ShipCountry}, BillAddr1: {BillAddr1}, BillCity: {BillCity}, BillState: {BillState}, BillZip: {BillZip}, BillCountry: {BillCountry}, Courier: {Courier}, TotalPrice: {TotalPrice}, BillToFirstName: {BillToFirstName}, BillToLastName: {BillToLastName}, ShipToFirstName: {ShipToFirstName}, ShipToLastName: {ShipToLastName}, AuthorizationNumber: {AuthorizationNumber}, Locale: {Locale}, LineNum: {LineNum}, Quantity: {Quantity}, UnitPrice: {UnitPrice}, ProductId: {ProductId}, CategoryId: {CategoryId}, ItemId: {ItemId}")]
    public partial class VwALLOrdersExtendedInfo : EntityBase
    {
        #region Static Constructor
        
        /// <summary>
        /// Initializes the <see cref="Account"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static VwALLOrdersExtendedInfo()
        {
            AddSharedRules();
        }
        
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Account"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public VwALLOrdersExtendedInfo()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        protected override void Initialize()
        {
            OnCreated();
        }
        
        #endregion
        
        #region Column Mapped Properties
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Int32 _orderId;
        
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.Int32 OrderId
        {
            get { return _orderId; }
            set
            {
                OnOrderIdChanging(value, _orderId);
                SendPropertyChanging("OrderId");
                _orderId = value;
                SendPropertyChanged("OrderId");
                OnOrderIdChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _userId;
        
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String UserId
        {
            get { return _userId; }
            set
            {
                OnUserIdChanging(value, _userId);
                SendPropertyChanging("UserId");
                _userId = value;
                SendPropertyChanged("UserId");
                OnUserIdChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.DateTime _orderDate;
        
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.DateTime OrderDate
        {
            get { return _orderDate; }
            set
            {
                OnOrderDateChanging(value, _orderDate);
                SendPropertyChanging("OrderDate");
                _orderDate = value;
                SendPropertyChanged("OrderDate");
                OnOrderDateChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _shipAddr1;
        
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String ShipAddr1
        {
            get { return _shipAddr1; }
            set
            {
                OnShipAddr1Changing(value, _shipAddr1);
                SendPropertyChanging("ShipAddr1");
                _shipAddr1 = value;
                SendPropertyChanged("ShipAddr1");
                OnShipAddr1Changed(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _shipCity;
        
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String ShipCity
        {
            get { return _shipCity; }
            set
            {
                OnShipCityChanging(value, _shipCity);
                SendPropertyChanging("ShipCity");
                _shipCity = value;
                SendPropertyChanged("ShipCity");
                OnShipCityChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _shipState;
        
        [System.Runtime.Serialization.DataMember(Order = 6)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String ShipState
        {
            get { return _shipState; }
            set
            {
                OnShipStateChanging(value, _shipState);
                SendPropertyChanging("ShipState");
                _shipState = value;
                SendPropertyChanged("ShipState");
                OnShipStateChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _shipZip;
        
        [System.Runtime.Serialization.DataMember(Order = 7)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String ShipZip
        {
            get { return _shipZip; }
            set
            {
                OnShipZipChanging(value, _shipZip);
                SendPropertyChanging("ShipZip");
                _shipZip = value;
                SendPropertyChanged("ShipZip");
                OnShipZipChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _shipCountry;
        
        [System.Runtime.Serialization.DataMember(Order = 8)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String ShipCountry
        {
            get { return _shipCountry; }
            set
            {
                OnShipCountryChanging(value, _shipCountry);
                SendPropertyChanging("ShipCountry");
                _shipCountry = value;
                SendPropertyChanged("ShipCountry");
                OnShipCountryChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _billAddr1;
        
        [System.Runtime.Serialization.DataMember(Order = 9)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String BillAddr1
        {
            get { return _billAddr1; }
            set
            {
                OnBillAddr1Changing(value, _billAddr1);
                SendPropertyChanging("BillAddr1");
                _billAddr1 = value;
                SendPropertyChanged("BillAddr1");
                OnBillAddr1Changed(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _billCity;
        
        [System.Runtime.Serialization.DataMember(Order = 10)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String BillCity
        {
            get { return _billCity; }
            set
            {
                OnBillCityChanging(value, _billCity);
                SendPropertyChanging("BillCity");
                _billCity = value;
                SendPropertyChanged("BillCity");
                OnBillCityChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _billState;
        
        [System.Runtime.Serialization.DataMember(Order = 11)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String BillState
        {
            get { return _billState; }
            set
            {
                OnBillStateChanging(value, _billState);
                SendPropertyChanging("BillState");
                _billState = value;
                SendPropertyChanged("BillState");
                OnBillStateChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _billZip;
        
        [System.Runtime.Serialization.DataMember(Order = 12)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String BillZip
        {
            get { return _billZip; }
            set
            {
                OnBillZipChanging(value, _billZip);
                SendPropertyChanging("BillZip");
                _billZip = value;
                SendPropertyChanged("BillZip");
                OnBillZipChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _billCountry;
        
        [System.Runtime.Serialization.DataMember(Order = 13)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String BillCountry
        {
            get { return _billCountry; }
            set
            {
                OnBillCountryChanging(value, _billCountry);
                SendPropertyChanging("BillCountry");
                _billCountry = value;
                SendPropertyChanged("BillCountry");
                OnBillCountryChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _courier;
        
        [System.Runtime.Serialization.DataMember(Order = 14)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String Courier
        {
            get { return _courier; }
            set
            {
                OnCourierChanging(value, _courier);
                SendPropertyChanging("Courier");
                _courier = value;
                SendPropertyChanged("Courier");
                OnCourierChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Decimal _totalPrice;
        
        [System.Runtime.Serialization.DataMember(Order = 15)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.Decimal TotalPrice
        {
            get { return _totalPrice; }
            set
            {
                OnTotalPriceChanging(value, _totalPrice);
                SendPropertyChanging("TotalPrice");
                _totalPrice = value;
                SendPropertyChanged("TotalPrice");
                OnTotalPriceChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _billToFirstName;
        
        [System.Runtime.Serialization.DataMember(Order = 16)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String BillToFirstName
        {
            get { return _billToFirstName; }
            set
            {
                OnBillToFirstNameChanging(value, _billToFirstName);
                SendPropertyChanging("BillToFirstName");
                _billToFirstName = value;
                SendPropertyChanged("BillToFirstName");
                OnBillToFirstNameChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _billToLastName;
        
        [System.Runtime.Serialization.DataMember(Order = 17)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String BillToLastName
        {
            get { return _billToLastName; }
            set
            {
                OnBillToLastNameChanging(value, _billToLastName);
                SendPropertyChanging("BillToLastName");
                _billToLastName = value;
                SendPropertyChanged("BillToLastName");
                OnBillToLastNameChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _shipToFirstName;
        
        [System.Runtime.Serialization.DataMember(Order = 18)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String ShipToFirstName
        {
            get { return _shipToFirstName; }
            set
            {
                OnShipToFirstNameChanging(value, _shipToFirstName);
                SendPropertyChanging("ShipToFirstName");
                _shipToFirstName = value;
                SendPropertyChanged("ShipToFirstName");
                OnShipToFirstNameChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _shipToLastName;
        
        [System.Runtime.Serialization.DataMember(Order = 19)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String ShipToLastName
        {
            get { return _shipToLastName; }
            set
            {
                OnShipToLastNameChanging(value, _shipToLastName);
                SendPropertyChanging("ShipToLastName");
                _shipToLastName = value;
                SendPropertyChanged("ShipToLastName");
                OnShipToLastNameChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Int32 _authorizationNumber;
        
        [System.Runtime.Serialization.DataMember(Order = 20)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.Int32 AuthorizationNumber
        {
            get { return _authorizationNumber; }
            set
            {
                OnAuthorizationNumberChanging(value, _authorizationNumber);
                SendPropertyChanging("AuthorizationNumber");
                _authorizationNumber = value;
                SendPropertyChanged("AuthorizationNumber");
                OnAuthorizationNumberChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _locale;
        
        [System.Runtime.Serialization.DataMember(Order = 21)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String Locale
        {
            get { return _locale; }
            set
            {
                OnLocaleChanging(value, _locale);
                SendPropertyChanging("Locale");
                _locale = value;
                SendPropertyChanged("Locale");
                OnLocaleChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Int32 _lineNum;
        
        [System.Runtime.Serialization.DataMember(Order = 22)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.Int32 LineNum
        {
            get { return _lineNum; }
            set
            {
                OnLineNumChanging(value, _lineNum);
                SendPropertyChanging("LineNum");
                _lineNum = value;
                SendPropertyChanged("LineNum");
                OnLineNumChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Int32 _quantity;
        
        [System.Runtime.Serialization.DataMember(Order = 23)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.Int32 Quantity
        {
            get { return _quantity; }
            set
            {
                OnQuantityChanging(value, _quantity);
                SendPropertyChanging("Quantity");
                _quantity = value;
                SendPropertyChanged("Quantity");
                OnQuantityChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Decimal _unitPrice;
        
        [System.Runtime.Serialization.DataMember(Order = 24)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.Decimal UnitPrice
        {
            get { return _unitPrice; }
            set
            {
                OnUnitPriceChanging(value, _unitPrice);
                SendPropertyChanging("UnitPrice");
                _unitPrice = value;
                SendPropertyChanged("UnitPrice");
                OnUnitPriceChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _productId;
        
        [System.Runtime.Serialization.DataMember(Order = 25)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String ProductId
        {
            get { return _productId; }
            set
            {
                OnProductIdChanging(value, _productId);
                SendPropertyChanging("ProductId");
                _productId = value;
                SendPropertyChanged("ProductId");
                OnProductIdChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _categoryId;
        
        [System.Runtime.Serialization.DataMember(Order = 26)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String CategoryId
        {
            get { return _categoryId; }
            set
            {
                OnCategoryIdChanging(value, _categoryId);
                SendPropertyChanging("CategoryId");
                _categoryId = value;
                SendPropertyChanged("CategoryId");
                OnCategoryIdChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _itemId;
        
        [System.Runtime.Serialization.DataMember(Order = 27)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String ItemId
        {
            get { return _itemId; }
            set
            {
                OnItemIdChanging(value, _itemId);
                SendPropertyChanging("ItemId");
                _itemId = value;
                SendPropertyChanged("ItemId");
                OnItemIdChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _shipAddr2;
        
        [System.Runtime.Serialization.DataMember(Order = 28)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String ShipAddr2
        {
            get { return _shipAddr2; }
            set
            {
                OnShipAddr2Changing(value, _shipAddr2);
                SendPropertyChanging("ShipAddr2");
                _shipAddr2 = value;
                SendPropertyChanged("ShipAddr2");
                OnShipAddr2Changed(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _billAddr2;
        
        [System.Runtime.Serialization.DataMember(Order = 29)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String BillAddr2
        {
            get { return _billAddr2; }
            set
            {
                OnBillAddr2Changing(value, _billAddr2);
                SendPropertyChanging("BillAddr2");
                _billAddr2 = value;
                SendPropertyChanged("BillAddr2");
                OnBillAddr2Changed(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _productName;
        
        [System.Runtime.Serialization.DataMember(Order = 30)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String ProductName
        {
            get { return _productName; }
            set
            {
                OnProductNameChanging(value, _productName);
                SendPropertyChanging("ProductName");
                _productName = value;
                SendPropertyChanged("ProductName");
                OnProductNameChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _descn;
        
        [System.Runtime.Serialization.DataMember(Order = 31)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String Descn
        {
            get { return _descn; }
            set
            {
                OnDescnChanging(value, _descn);
                SendPropertyChanging("Descn");
                _descn = value;
                SendPropertyChanged("Descn");
                OnDescnChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _productImage;
        
        [System.Runtime.Serialization.DataMember(Order = 32)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String ProductImage
        {
            get { return _productImage; }
            set
            {
                OnProductImageChanging(value, _productImage);
                SendPropertyChanging("ProductImage");
                _productImage = value;
                SendPropertyChanged("ProductImage");
                OnProductImageChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Decimal? _listPrice;
        
        [System.Runtime.Serialization.DataMember(Order = 33)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.Decimal? ListPrice
        {
            get { return _listPrice; }
            set
            {
                OnListPriceChanging(value, _listPrice);
                SendPropertyChanging("ListPrice");
                _listPrice = value;
                SendPropertyChanged("ListPrice");
                OnListPriceChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Decimal? _unitCost;
        
        [System.Runtime.Serialization.DataMember(Order = 34)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.Decimal? UnitCost
        {
            get { return _unitCost; }
            set
            {
                OnUnitCostChanging(value, _unitCost);
                SendPropertyChanging("UnitCost");
                _unitCost = value;
                SendPropertyChanged("UnitCost");
                OnUnitCostChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Int32? _supplier;
        
        [System.Runtime.Serialization.DataMember(Order = 35)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.Int32? Supplier
        {
            get { return _supplier; }
            set
            {
                OnSupplierChanging(value, _supplier);
                SendPropertyChanging("Supplier");
                _supplier = value;
                SendPropertyChanged("Supplier");
                OnSupplierChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _status;
        
        [System.Runtime.Serialization.DataMember(Order = 36)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String Status
        {
            get { return _status; }
            set
            {
                OnStatusChanging(value, _status);
                SendPropertyChanging("Status");
                _status = value;
                SendPropertyChanged("Status");
                OnStatusChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _itemName;
        
        [System.Runtime.Serialization.DataMember(Order = 37)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String ItemName
        {
            get { return _itemName; }
            set
            {
                OnItemNameChanging(value, _itemName);
                SendPropertyChanging("ItemName");
                _itemName = value;
                SendPropertyChanged("ItemName");
                OnItemNameChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _itemImage;
        
        [System.Runtime.Serialization.DataMember(Order = 38)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String ItemImage
        {
            get { return _itemImage; }
            set
            {
                OnItemImageChanging(value, _itemImage);
                SendPropertyChanging("ItemImage");
                _itemImage = value;
                SendPropertyChanged("ItemImage");
                OnItemImageChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.String _categoryName;
        
        [System.Runtime.Serialization.DataMember(Order = 39)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual System.String CategoryName
        {
            get { return _categoryName; }
            set
            {
                OnCategoryNameChanging(value, _categoryName);
                SendPropertyChanging("CategoryName");
                _categoryName = value;
                SendPropertyChanged("CategoryName");
                OnCategoryNameChanged(value);
            }
        }
        
        #endregion
        
        #region Associations Mappings
        
        #endregion
        
        #region Composite Key Overrides
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public override bool Equals(object obj)
        {
            var entity = obj as VwALLOrdersExtendedInfo;
            if (entity == null)
                return false;

            return 
                OrderId == entity.OrderId
                && UserId == entity.UserId
                && OrderDate == entity.OrderDate
                && ShipAddr1 == entity.ShipAddr1
                && ShipCity == entity.ShipCity
                && ShipState == entity.ShipState
                && ShipZip == entity.ShipZip
                && ShipCountry == entity.ShipCountry
                && BillAddr1 == entity.BillAddr1
                && BillCity == entity.BillCity
                && BillState == entity.BillState
                && BillZip == entity.BillZip
                && BillCountry == entity.BillCountry
                && Courier == entity.Courier
                && TotalPrice == entity.TotalPrice
                && BillToFirstName == entity.BillToFirstName
                && BillToLastName == entity.BillToLastName
                && ShipToFirstName == entity.ShipToFirstName
                && ShipToLastName == entity.ShipToLastName
                && AuthorizationNumber == entity.AuthorizationNumber
                && Locale == entity.Locale
                && LineNum == entity.LineNum
                && Quantity == entity.Quantity
                && UnitPrice == entity.UnitPrice
                && ProductId == entity.ProductId
                && CategoryId == entity.CategoryId
                && ItemId == entity.ItemId;
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public override int GetHashCode()
        {
            return (
                OrderId
                + "|" + UserId
                + "|" + OrderDate
                + "|" + ShipAddr1
                + "|" + ShipCity
                + "|" + ShipState
                + "|" + ShipZip
                + "|" + ShipCountry
                + "|" + BillAddr1
                + "|" + BillCity
                + "|" + BillState
                + "|" + BillZip
                + "|" + BillCountry
                + "|" + Courier
                + "|" + TotalPrice
                + "|" + BillToFirstName
                + "|" + BillToLastName
                + "|" + ShipToFirstName
                + "|" + ShipToLastName
                + "|" + AuthorizationNumber
                + "|" + Locale
                + "|" + LineNum
                + "|" + Quantity
                + "|" + UnitPrice
                + "|" + ProductId
                + "|" + CategoryId
                + "|" + ItemId
                ).GetHashCode();
        }
        
        #endregion
        
        #region Extensibility Method
        
        static partial void AddSharedRules();
        
        partial void OnCreated();
        
        partial void OnOrderIdChanging(System.Int32 newValue, System.Int32 oldValue);
        
        partial void OnOrderIdChanged(System.Int32 value);
        
        partial void OnUserIdChanging(System.String newValue, System.String oldValue);
        
        partial void OnUserIdChanged(System.String value);
        
        partial void OnOrderDateChanging(System.DateTime newValue, System.DateTime oldValue);
        
        partial void OnOrderDateChanged(System.DateTime value);
        
        partial void OnShipAddr1Changing(System.String newValue, System.String oldValue);
        
        partial void OnShipAddr1Changed(System.String value);
        
        partial void OnShipCityChanging(System.String newValue, System.String oldValue);
        
        partial void OnShipCityChanged(System.String value);
        
        partial void OnShipStateChanging(System.String newValue, System.String oldValue);
        
        partial void OnShipStateChanged(System.String value);
        
        partial void OnShipZipChanging(System.String newValue, System.String oldValue);
        
        partial void OnShipZipChanged(System.String value);
        
        partial void OnShipCountryChanging(System.String newValue, System.String oldValue);
        
        partial void OnShipCountryChanged(System.String value);
        
        partial void OnBillAddr1Changing(System.String newValue, System.String oldValue);
        
        partial void OnBillAddr1Changed(System.String value);
        
        partial void OnBillCityChanging(System.String newValue, System.String oldValue);
        
        partial void OnBillCityChanged(System.String value);
        
        partial void OnBillStateChanging(System.String newValue, System.String oldValue);
        
        partial void OnBillStateChanged(System.String value);
        
        partial void OnBillZipChanging(System.String newValue, System.String oldValue);
        
        partial void OnBillZipChanged(System.String value);
        
        partial void OnBillCountryChanging(System.String newValue, System.String oldValue);
        
        partial void OnBillCountryChanged(System.String value);
        
        partial void OnCourierChanging(System.String newValue, System.String oldValue);
        
        partial void OnCourierChanged(System.String value);
        
        partial void OnTotalPriceChanging(System.Decimal newValue, System.Decimal oldValue);
        
        partial void OnTotalPriceChanged(System.Decimal value);
        
        partial void OnBillToFirstNameChanging(System.String newValue, System.String oldValue);
        
        partial void OnBillToFirstNameChanged(System.String value);
        
        partial void OnBillToLastNameChanging(System.String newValue, System.String oldValue);
        
        partial void OnBillToLastNameChanged(System.String value);
        
        partial void OnShipToFirstNameChanging(System.String newValue, System.String oldValue);
        
        partial void OnShipToFirstNameChanged(System.String value);
        
        partial void OnShipToLastNameChanging(System.String newValue, System.String oldValue);
        
        partial void OnShipToLastNameChanged(System.String value);
        
        partial void OnAuthorizationNumberChanging(System.Int32 newValue, System.Int32 oldValue);
        
        partial void OnAuthorizationNumberChanged(System.Int32 value);
        
        partial void OnLocaleChanging(System.String newValue, System.String oldValue);
        
        partial void OnLocaleChanged(System.String value);
        
        partial void OnLineNumChanging(System.Int32 newValue, System.Int32 oldValue);
        
        partial void OnLineNumChanged(System.Int32 value);
        
        partial void OnQuantityChanging(System.Int32 newValue, System.Int32 oldValue);
        
        partial void OnQuantityChanged(System.Int32 value);
        
        partial void OnUnitPriceChanging(System.Decimal newValue, System.Decimal oldValue);
        
        partial void OnUnitPriceChanged(System.Decimal value);
        
        partial void OnProductIdChanging(System.String newValue, System.String oldValue);
        
        partial void OnProductIdChanged(System.String value);
        
        partial void OnCategoryIdChanging(System.String newValue, System.String oldValue);
        
        partial void OnCategoryIdChanged(System.String value);
        
        partial void OnItemIdChanging(System.String newValue, System.String oldValue);
        
        partial void OnItemIdChanged(System.String value);
        
        partial void OnShipAddr2Changing(System.String newValue, System.String oldValue);
        
        partial void OnShipAddr2Changed(System.String value);
        
        partial void OnBillAddr2Changing(System.String newValue, System.String oldValue);
        
        partial void OnBillAddr2Changed(System.String value);
        
        partial void OnProductNameChanging(System.String newValue, System.String oldValue);
        
        partial void OnProductNameChanged(System.String value);
        
        partial void OnDescnChanging(System.String newValue, System.String oldValue);
        
        partial void OnDescnChanged(System.String value);
        
        partial void OnProductImageChanging(System.String newValue, System.String oldValue);
        
        partial void OnProductImageChanged(System.String value);
        
        partial void OnListPriceChanging(System.Decimal? newValue, System.Decimal? oldValue);
        
        partial void OnListPriceChanged(System.Decimal? value);
        
        partial void OnUnitCostChanging(System.Decimal? newValue, System.Decimal? oldValue);
        
        partial void OnUnitCostChanged(System.Decimal? value);
        
        partial void OnSupplierChanging(System.Int32? newValue, System.Int32? oldValue);
        
        partial void OnSupplierChanged(System.Int32? value);
        
        partial void OnStatusChanging(System.String newValue, System.String oldValue);
        
        partial void OnStatusChanged(System.String value);
        
        partial void OnItemNameChanging(System.String newValue, System.String oldValue);
        
        partial void OnItemNameChanged(System.String value);
        
        partial void OnItemImageChanging(System.String newValue, System.String oldValue);
        
        partial void OnItemImageChanged(System.String value);
        
        partial void OnCategoryNameChanging(System.String newValue, System.String oldValue);
        
        partial void OnCategoryNameChanged(System.String value);
        
        
        #endregion
        
        #region Clone
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public virtual VwALLOrdersExtendedInfo Clone()
        {
            return (VwALLOrdersExtendedInfo)((ICloneable)this).Clone();
        }
        
        #endregion
        
        #region Serialization
        
        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static VwALLOrdersExtendedInfo FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(VwALLOrdersExtendedInfo));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as VwALLOrdersExtendedInfo;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static VwALLOrdersExtendedInfo FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(VwALLOrdersExtendedInfo));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as VwALLOrdersExtendedInfo;
            }
        }
        
        #endregion
    }
}

#pragma warning restore 1591
#pragma warning restore 0414

