<?xml version="1.0" encoding="utf-8"?>
<Database Name="Sample" EntityNamespace="Sample.Data" ContextNamespace="Sample.Data" Class="SampleDataContext" EntityBase="LinqEntityBase" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection ConnectionString="Data Source=zeus;Initial Catalog=Sample;Integrated Security=True" SettingsObjectName="Properties.Settings" SettingsPropertyName="SampleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ActiveUser" Member="ActiveUser">
    <Type Name="ActiveUser">
      <Column Name="UserID" Storage="_userID" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Storage="_userName" Type="System.String" DbType="varchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Storage="_password" Type="System.String" DbType="varchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Storage="_email" Type="System.String" DbType="varchar(150)" CanBeNull="true" />
      <Column Name="FirstName" Storage="_firstName" Type="System.String" DbType="varchar(100)" CanBeNull="true" />
      <Column Name="LastName" Storage="_lastName" Type="System.String" DbType="varchar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Priority" Member="Priority">
    <Type Name="Priority">
      <Column Name="PriorityID" Storage="_priorityID" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PriorityName" Storage="_priorityName" Type="System.String" DbType="varchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Storage="_displayOrder" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Association Name="Priority_Task" Member="TaskList" Storage="_taskList" OtherKey="PriorityID" Type="Task" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Role">
    <Type Name="Role">
      <Column Name="RoleID" Storage="_roleID" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Storage="_roleName" Type="System.String" DbType="varchar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="UserRoleList" Storage="_userRoleList" OtherKey="RoleID" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="Status">
    <Type Name="Status">
      <Column Name="StatusID" Storage="_statusID" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StatusName" Storage="_statusName" Type="System.String" DbType="varchar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Storage="_displayOrder" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Association Name="Status_Task" Member="TaskList" Storage="_taskList" OtherKey="StatusID" Type="Task" />
    </Type>
  </Table>
  <Table Name="dbo.Task" Member="Task">
    <Type Name="Task">
      <Column Name="TaskID" Storage="_taskID" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StatusID" Storage="_statusID" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="PriorityID" Storage="_priorityID" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedID" Storage="_createdID" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Storage="_createDate" Type="System.DateTime" DbType="datetime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Storage="_updateDate" Type="System.DateTime" DbType="datetime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Storage="_summary" Type="System.String" DbType="varchar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Details" Storage="_details" Type="System.String" DbType="varchar(2000)" CanBeNull="true" />
      <Column Name="StartDate" Storage="_startDate" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Column Name="DueDate" Storage="_dueDate" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Column Name="CompleteDate" Storage="_completeDate" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Column Name="AssignedID" Storage="_assignedID" Type="System.Int32" DbType="int" CanBeNull="true" />
      <Association Name="Priority_Task" Member="Priority" Storage="_priority" ThisKey="PriorityID" Type="Priority" IsForeignKey="true" />
      <Association Name="Status_Task" Member="Status" Storage="_status" ThisKey="StatusID" Type="Status" IsForeignKey="true" />
      <Association Name="User_Task" Member="CreatedUser" Storage="_createdUser" ThisKey="AssignedID" Type="User" IsForeignKey="true" />
      <Association Name="Task_TaskExtended" Member="TaskExtended" Storage="_taskExtended" OtherKey="TaskID" Type="TaskExtended" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.TaskExtended" Member="TaskExtended">
    <Type Name="TaskExtended">
      <Column Name="TaskID" Storage="_taskID" Type="System.Int32" DbType="int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Browser" Storage="_browser" Type="System.String" DbType="nvarchar(200)" CanBeNull="true" />
      <Column Name="OS" Storage="_oS" Type="System.String" DbType="nvarchar(150)" CanBeNull="true" />
      <Association Name="Task_TaskExtended" Member="Task" Storage="_task" ThisKey="TaskID" Type="Task" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.User" Member="User">
    <Type Name="User">
      <Column Name="UserID" Storage="_userID" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Storage="_userName" Type="System.String" DbType="varchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Storage="_password" Type="System.String" DbType="varchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Storage="_email" Type="System.String" DbType="varchar(150)" CanBeNull="true" />
      <Column Name="FirstName" Storage="_firstName" Type="System.String" DbType="varchar(100)" CanBeNull="true" />
      <Column Name="LastName" Storage="_lastName" Type="System.String" DbType="varchar(100)" CanBeNull="true" />
      <Column Name="Avatar" Storage="_avatar" Type="System.Byte[]" DbType="image" CanBeNull="true" />
      <Column Name="CreateDate" Storage="_createDate" Type="System.DateTime" DbType="datetime NOT NULL" CanBeNull="false" />
      <Association Name="User_Task" Member="CreatedTaskList" Storage="_createdTaskList" OtherKey="AssignedID" Type="Task" />
      <Association Name="User_UserRole" Member="UserRoleList" Storage="_userRoleList" OtherKey="UserID" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRole">
    <Type Name="UserRole">
      <Column Name="UserID" Storage="_userID" Type="System.Int32" DbType="int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleID" Storage="_roleID" Type="System.Int32" DbType="int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="Role" Storage="_role" ThisKey="RoleID" Type="Role" IsForeignKey="true" />
      <Association Name="User_UserRole" Member="User" Storage="_user" ThisKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetEmail" Method="GetEmail">
    <Parameter Name="@userName" Parameter="userName" Type="System.String" DbType="varchar(20)" />
    <Parameter Name="@email" Parameter="email" Type="System.String" DbType="varchar(150)" Direction="InOut" />
    <Return Type="System.Int32" DbType="int" />
  </Function>
  <Function Name="dbo.GetMyTasks" Method="GetMyTasks">
    <Parameter Name="@userID" Parameter="userID" Type="System.Int32" DbType="int" />
    <ElementType Name="GetMyTasksResult">
      <Column Name="TaskID" Storage="_taskID" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Storage="_statusID" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="PriorityID" Storage="_priorityID" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedID" Storage="_createdID" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Storage="_createDate" Type="System.DateTime" DbType="datetime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Storage="_updateDate" Type="System.DateTime" DbType="datetime NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Storage="_summary" Type="System.String" DbType="varchar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Details" Storage="_details" Type="System.String" DbType="varchar(2000)" CanBeNull="true" />
      <Column Name="StartDate" Storage="_startDate" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Column Name="DueDate" Storage="_dueDate" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Column Name="CompleteDate" Storage="_completeDate" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Column Name="AssignedID" Storage="_assignedID" Type="System.Int32" DbType="int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MarkTaskComplete" Method="MarkTaskComplete">
    <Parameter Name="@taskId" Parameter="taskId" Type="System.Int32" DbType="int" />
    <Return Type="System.Int32" DbType="int" />
  </Function>
</Database>