<?xml version="1.0" encoding="utf-8"?>
<Database Name="Petshop" EntityNamespace="Petshop.Data" ContextNamespace="Petshop.Data" Class="PetshopDataContext" EntityBase="LinqEntityBase" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection ConnectionString="Data Source=TDUPONT-LT;Initial Catalog=Petshop;Integrated Security=True" SettingsObjectName="Properties.Settings" SettingsPropertyName="PetshopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Account">
    <Type Name="Account">
      <Column Name="AccountID" Storage="_accountID" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UniqueID" Storage="_uniqueID" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Storage="_email" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Storage="_firstName" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Storage="_lastName" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Storage="_address1" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Storage="_address2" Type="System.String" DbType="varchar(80)" CanBeNull="true" />
      <Column Name="City" Storage="_city" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="State" Storage="_state" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Zip" Storage="_zip" Type="System.String" DbType="varchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Storage="_country" Type="System.String" DbType="varchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Storage="_phone" Type="System.String" DbType="varchar(20)" CanBeNull="true" />
      <Association Name="Profiles_Account" Member="Profiles" Storage="_profiles" ThisKey="UniqueID" Type="Profiles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cart" Member="Cart">
    <Type Name="Cart">
      <Column Name="CartID" Storage="_cartID" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UniqueID" Storage="_uniqueID" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="ItemId" Storage="_itemId" Type="System.String" DbType="varchar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Storage="_name" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Storage="_type" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Storage="_price" Type="System.Decimal" DbType="decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Storage="_categoryId" Type="System.String" DbType="varchar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProductId" Storage="_productId" Type="System.String" DbType="varchar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IsShoppingCart" Storage="_isShoppingCart" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Storage="_quantity" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Association Name="Profiles_Cart" Member="Profiles" Storage="_profiles" ThisKey="UniqueID" Type="Profiles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Category">
    <Type Name="Category">
      <Column Name="CategoryId" Storage="_categoryId" Type="System.String" DbType="varchar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Storage="_name" Type="System.String" DbType="varchar(80)" CanBeNull="true" />
      <Column Name="Descn" Storage="_descn" Type="System.String" DbType="varchar(255)" CanBeNull="true" />
      <Association Name="Category_Product" Member="ProductList" Storage="_productList" OtherKey="CategoryId" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Inventory" Member="Inventory">
    <Type Name="Inventory">
      <Column Name="ItemId" Storage="_itemId" Type="System.String" DbType="varchar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Qty" Storage="_qty" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Item" Member="Item">
    <Type Name="Item">
      <Column Name="ItemId" Storage="_itemId" Type="System.String" DbType="varchar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductId" Storage="_productId" Type="System.String" DbType="varchar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ListPrice" Storage="_listPrice" Type="System.Decimal" DbType="decimal(10,2)" CanBeNull="true" />
      <Column Name="UnitCost" Storage="_unitCost" Type="System.Decimal" DbType="decimal(10,2)" CanBeNull="true" />
      <Column Name="Supplier" Storage="_supplier" Type="System.Int32" DbType="int" CanBeNull="true" />
      <Column Name="Status" Storage="_status" Type="System.String" DbType="varchar(2)" CanBeNull="true" />
      <Column Name="Name" Storage="_name" Type="System.String" DbType="varchar(80)" CanBeNull="true" />
      <Column Name="Image" Storage="_image" Type="System.String" DbType="varchar(80)" CanBeNull="true" />
      <Association Name="Product_Item" Member="Product" Storage="_product" ThisKey="ProductId" Type="Product" IsForeignKey="true" />
      <Association Name="Supplier_Item" Member="Supplier1" Storage="_supplier1" ThisKey="Supplier" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LineItem" Member="LineItem">
    <Type Name="LineItem">
      <Column Name="OrderId" Storage="_orderId" Type="System.Int32" DbType="int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LineNum" Storage="_lineNum" Type="System.Int32" DbType="int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ItemId" Storage="_itemId" Type="System.String" DbType="varchar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Storage="_quantity" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Storage="_unitPrice" Type="System.Decimal" DbType="decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="Orders_LineItem" Member="Orders" Storage="_orders" ThisKey="OrderId" Type="Orders" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Orders">
      <Column Name="OrderId" Storage="_orderId" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Storage="_userId" Type="System.String" DbType="varchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="OrderDate" Storage="_orderDate" Type="System.DateTime" DbType="datetime NOT NULL" CanBeNull="false" />
      <Column Name="ShipAddr1" Storage="_shipAddr1" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ShipAddr2" Storage="_shipAddr2" Type="System.String" DbType="varchar(80)" CanBeNull="true" />
      <Column Name="ShipCity" Storage="_shipCity" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ShipState" Storage="_shipState" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ShipZip" Storage="_shipZip" Type="System.String" DbType="varchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ShipCountry" Storage="_shipCountry" Type="System.String" DbType="varchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="BillAddr1" Storage="_billAddr1" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="BillAddr2" Storage="_billAddr2" Type="System.String" DbType="varchar(80)" CanBeNull="true" />
      <Column Name="BillCity" Storage="_billCity" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="BillState" Storage="_billState" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="BillZip" Storage="_billZip" Type="System.String" DbType="varchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="BillCountry" Storage="_billCountry" Type="System.String" DbType="varchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Courier" Storage="_courier" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="TotalPrice" Storage="_totalPrice" Type="System.Decimal" DbType="decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="BillToFirstName" Storage="_billToFirstName" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="BillToLastName" Storage="_billToLastName" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ShipToFirstName" Storage="_shipToFirstName" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ShipToLastName" Storage="_shipToLastName" Type="System.String" DbType="varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorizationNumber" Storage="_authorizationNumber" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="Locale" Storage="_locale" Type="System.String" DbType="varchar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Orders_LineItem" Member="LineItemList" Storage="_lineItemList" OtherKey="OrderId" Type="LineItem" />
      <Association Name="Orders_OrderStatus" Member="OrderStatusList" Storage="_orderStatusList" OtherKey="OrderId" Type="OrderStatus" />
    </Type>
  </Table>
  <Table Name="dbo.OrderStatus" Member="OrderStatus">
    <Type Name="OrderStatus">
      <Column Name="OrderId" Storage="_orderId" Type="System.Int32" DbType="int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LineNum" Storage="_lineNum" Type="System.Int32" DbType="int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Timestamp" Storage="_timestamp" Type="System.DateTime" DbType="datetime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Storage="_status" Type="System.String" DbType="varchar(2) NOT NULL" CanBeNull="false" />
      <Association Name="Orders_OrderStatus" Member="Orders" Storage="_orders" ThisKey="OrderId" Type="Orders" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Product">
    <Type Name="Product">
      <Column Name="ProductId" Storage="_productId" Type="System.String" DbType="varchar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryId" Storage="_categoryId" Type="System.String" DbType="varchar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Storage="_name" Type="System.String" DbType="varchar(80)" CanBeNull="true" />
      <Column Name="Descn" Storage="_descn" Type="System.String" DbType="varchar(255)" CanBeNull="true" />
      <Column Name="Image" Storage="_image" Type="System.String" DbType="varchar(80)" CanBeNull="true" />
      <Association Name="Product_Item" Member="ItemList" Storage="_itemList" OtherKey="ProductId" Type="Item" />
      <Association Name="Category_Product" Member="Category" Storage="_category" ThisKey="CategoryId" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Profiles" Member="Profiles">
    <Type Name="Profiles">
      <Column Name="UniqueID" Storage="_uniqueID" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Storage="_username" Type="System.String" DbType="varchar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationName" Storage="_applicationName" Type="System.String" DbType="varchar(256) NOT NULL" CanBeNull="false" />
      <Column Name="IsAnonymous" Storage="_isAnonymous" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="LastActivityDate" Storage="_lastActivityDate" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Column Name="LastUpdatedDate" Storage="_lastUpdatedDate" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Association Name="Profiles_Account" Member="AccountList" Storage="_accountList" OtherKey="UniqueID" Type="Account" />
      <Association Name="Profiles_Cart" Member="CartList" Storage="_cartList" OtherKey="UniqueID" Type="Cart" />
    </Type>
  </Table>
  <Table Name="dbo.Supplier" Member="Supplier">
    <Type Name="Supplier">
      <Column Name="SuppId" Storage="_suppId" Type="System.Int32" DbType="int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Storage="_name" Type="System.String" DbType="varchar(80)" CanBeNull="true" />
      <Column Name="Status" Storage="_status" Type="System.String" DbType="varchar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Addr1" Storage="_addr1" Type="System.String" DbType="varchar(80)" CanBeNull="true" />
      <Column Name="Addr2" Storage="_addr2" Type="System.String" DbType="varchar(80)" CanBeNull="true" />
      <Column Name="City" Storage="_city" Type="System.String" DbType="varchar(80)" CanBeNull="true" />
      <Column Name="State" Storage="_state" Type="System.String" DbType="varchar(80)" CanBeNull="true" />
      <Column Name="Zip" Storage="_zip" Type="System.String" DbType="varchar(5)" CanBeNull="true" />
      <Column Name="Phone" Storage="_phone" Type="System.String" DbType="varchar(40)" CanBeNull="true" />
      <Association Name="Supplier_Item" Member="ItemList" Storage="_itemList" OtherKey="Supplier" Type="Item" />
    </Type>
  </Table>
</Database>